<?php

/**
 * @file
 * Code for the Vejlebib settings module.
 */

include_once 'vejlebib_settings.features.inc';

/**
 * Implements hook_init() (temporary for testing).
 */	
function vejlebib_settings_init() {

}

/**
 * Implements hook_menu_alter().
 */
function vejlebib_settings_menu_alter(&$items) {
	// The library app uses this path to collect data about opening hours. During
	// the transition from ding1 to ding2, all the libraries got new nids. At this
	// point in time, we are not able to correct the values in the app, so here we
	// employ a temporary hack, that maps the library nids to the correct ones.
	// This should be removed, once the values is corrected in the library app.
	if (isset($items['opening_hours/instances'])) {
		$item = &$items['opening_hours/instances'];
		$item['page callback'] = 'vejlebib_settings_opening_hours_crud_api_page';
	} 
}

/**
 * Wrapper function for the opening hours page callback.
 */
function vejlebib_settings_opening_hours_crud_api_page() {
	if ($_SERVER['REQUEST_METHOD'] == 'GET') {
		// Hard coded mappings from the old library nids to the new ones.
		$nid_mappings = array(
			// Vejle
			1 => 13,
			// Egtved
			2 => 16,
			// Jelling
			3 => 17,
			// Børkop
			35 => 15,
			// Give
			36 => 14,
			// Biblioteksbussen
			37 => 18,
		);
    // The nid parameter might be an array. We don't do any sanitizing here, as
    // it is handled by the original page callback in the opening hours module.
    $nids = explode(',', $_REQUEST['nid']);
    foreach ($nids as $key => $nid) {
    	if (in_array($nid, array_keys($nid_mappings))) {
    		$nids[$key] = $nid_mappings[$nid];
    	}
    }
    // Make sure the page callback gets the input it expects.
    $nids = implode(',', $nids);
    $_REQUEST['nid'] = $nids;
	}
	// Always fall thorugh to the original page callback from the opening hours
	// module.
	opening_hours_crud_api_page();
}

