<?php
/**
 * @file
 * vejlebib_settings.features.menu_links.inc
 */

/**
 * Implements hook_menu_default_menu_links().
 */
function vejlebib_settings_menu_default_menu_links() {
  $menu_links = array();

  // Exported menu link: menu-footer-menu-1:node/5465
  $menu_links['menu-footer-menu-1:node/5465'] = array(
    'menu_name' => 'menu-footer-menu-1',
    'link_path' => 'node/5465',
    'router_path' => 'node/%',
    'link_title' => 'Svært ved at læse?',
    'options' => array(
      'attributes' => array(
        'title' => 'Tilbud til dig, der har nedsat syn, er ordblind, er fremmedsproget og ved at lære dansk, eller er fysisk handicappet',
      ),
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -49,
  );
  // Exported menu link: menu-footer-menu-1:node/5471
  $menu_links['menu-footer-menu-1:node/5471'] = array(
    'menu_name' => 'menu-footer-menu-1',
    'link_path' => 'node/5471',
    'router_path' => 'node/%',
    'link_title' => 'Læsekredse',
    'options' => array(
      'attributes' => array(
        'title' => 'Læsekredsene i Vejle Kommune',
      ),
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -47,
  );
  // Exported menu link: menu-footer-menu-1:node/5518
  $menu_links['menu-footer-menu-1:node/5518'] = array(
    'menu_name' => 'menu-footer-menu-1',
    'link_path' => 'node/5518',
    'router_path' => 'node/%',
    'link_title' => 'Arrangementsklubben',
    'options' => array(
      'attributes' => array(
        'title' => 'Bliv medlem af Vejle Bibliotekernes arrangementsklub og få 50% rabat på arrangementer',
      ),
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -46,
  );
  // Exported menu link: menu-footer-menu-1:node/5584
  $menu_links['menu-footer-menu-1:node/5584'] = array(
    'menu_name' => 'menu-footer-menu-1',
    'link_path' => 'node/5584',
    'router_path' => 'node/%',
    'link_title' => 'Biblioteksintroduktion',
    'options' => array(
      'attributes' => array(
        'title' => 'Rundvisning og introduktion til biblioteket for foreninger, skoleklasser og grupper af andre interesserede',
      ),
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -45,
  );
  // Exported menu link: menu-footer-menu-1:node/5607
  $menu_links['menu-footer-menu-1:node/5607'] = array(
    'menu_name' => 'menu-footer-menu-1',
    'link_path' => 'node/5607',
    'router_path' => 'node/%',
    'link_title' => 'Gratis retshjælp',
    'options' => array(
      'attributes' => array(
        'title' => 'Advokaterne i Vejle tilbyder gratis retshjælp på Vejle Bibliotek',
      ),
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
  );
  // Exported menu link: menu-footer-menu-1:node/5645
  $menu_links['menu-footer-menu-1:node/5645'] = array(
    'menu_name' => 'menu-footer-menu-1',
    'link_path' => 'node/5645',
    'router_path' => 'node/%',
    'link_title' => 'DR Romanklubben',
    'options' => array(
      'attributes' => array(
        'title' => 'Læseklubber under DR Romanklub',
      ),
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -48,
  );
  // Exported menu link: menu-footer-menu-1:node/5711
  $menu_links['menu-footer-menu-1:node/5711'] = array(
    'menu_name' => 'menu-footer-menu-1',
    'link_path' => 'node/5711',
    'router_path' => 'node/%',
    'link_title' => 'Svært ved at komme på biblioteket?',
    'options' => array(
      'attributes' => array(
        'title' => '"Biblioteket Kommer" er en service, hvor vi bringer bøgerne ud til dig',
      ),
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
  );
  // Exported menu link: menu-footer-menu-2:node/13
  $menu_links['menu-footer-menu-2:node/13'] = array(
    'menu_name' => 'menu-footer-menu-2',
    'link_path' => 'node/13',
    'router_path' => 'node/%',
    'link_title' => 'Vejle Bibliotek',
    'options' => array(
      'attributes' => array(
        'title' => 'Vejle Bibliotek',
      ),
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
  );
  // Exported menu link: menu-footer-menu-2:node/14
  $menu_links['menu-footer-menu-2:node/14'] = array(
    'menu_name' => 'menu-footer-menu-2',
    'link_path' => 'node/14',
    'router_path' => 'node/%',
    'link_title' => 'Give Bibliotek',
    'options' => array(
      'attributes' => array(
        'title' => 'Give Bibliotek',
      ),
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
  );
  // Exported menu link: menu-footer-menu-2:node/15
  $menu_links['menu-footer-menu-2:node/15'] = array(
    'menu_name' => 'menu-footer-menu-2',
    'link_path' => 'node/15',
    'router_path' => 'node/%',
    'link_title' => 'Børkop Bibliotek',
    'options' => array(
      'attributes' => array(
        'title' => 'Børkop Bibliotek',
      ),
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
  );
  // Exported menu link: menu-footer-menu-2:node/16
  $menu_links['menu-footer-menu-2:node/16'] = array(
    'menu_name' => 'menu-footer-menu-2',
    'link_path' => 'node/16',
    'router_path' => 'node/%',
    'link_title' => 'Egtved Bibliotek',
    'options' => array(
      'attributes' => array(
        'title' => 'Egtved Bibliotek',
      ),
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
  );
  // Exported menu link: menu-footer-menu-2:node/17
  $menu_links['menu-footer-menu-2:node/17'] = array(
    'menu_name' => 'menu-footer-menu-2',
    'link_path' => 'node/17',
    'router_path' => 'node/%',
    'link_title' => 'Jelling Bibliotek',
    'options' => array(
      'attributes' => array(
        'title' => 'Jelling Bibliotek',
      ),
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
  );
  // Exported menu link: menu-footer-menu-2:node/18
  $menu_links['menu-footer-menu-2:node/18'] = array(
    'menu_name' => 'menu-footer-menu-2',
    'link_path' => 'node/18',
    'router_path' => 'node/%',
    'link_title' => 'Biblioteksbussen',
    'options' => array(
      'attributes' => array(
        'title' => 'Biblioteksbussen',
      ),
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
  );
  // Exported menu link: menu-footer-menu-3:node/5449
  $menu_links['menu-footer-menu-3:node/5449'] = array(
    'menu_name' => 'menu-footer-menu-3',
    'link_path' => 'node/5449',
    'router_path' => 'node/%',
    'link_title' => 'Bibliotekspolitik',
    'options' => array(
      'attributes' => array(
        'title' => 'Bibliotekspolitik for Vejle Bibliotekerne',
      ),
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -43,
  );
  // Exported menu link: menu-footer-menu-3:node/5450
  $menu_links['menu-footer-menu-3:node/5450'] = array(
    'menu_name' => 'menu-footer-menu-3',
    'link_path' => 'node/5450',
    'router_path' => 'node/%',
    'link_title' => 'Strategi 2011-2014',
    'options' => array(
      'attributes' => array(
        'title' => 'Vejle Bibliotekernes visioner og handlingsplaner',
      ),
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -44,
  );
  // Exported menu link: menu-footer-menu-3:node/5503
  $menu_links['menu-footer-menu-3:node/5503'] = array(
    'menu_name' => 'menu-footer-menu-3',
    'link_path' => 'node/5503',
    'router_path' => 'node/%',
    'link_title' => 'Centralbibliotek',
    'options' => array(
      'attributes' => array(
        'title' => 'Vejle Bibliotekerne er centralbibliotek for bibliotekerne i det sydlige Jylland og Middelfart Bibliotek',
      ),
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
  );
  // Exported menu link: menu-footer-menu-3:node/5579
  $menu_links['menu-footer-menu-3:node/5579'] = array(
    'menu_name' => 'menu-footer-menu-3',
    'link_path' => 'node/5579',
    'router_path' => 'node/%',
    'link_title' => 'Reglement',
    'options' => array(
      'attributes' => array(
        'title' => 'Vejle Bibliotekernes reglement',
      ),
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -45,
  );
  // Exported menu link: menu-footer-menu-3:node/5638
  $menu_links['menu-footer-menu-3:node/5638'] = array(
    'menu_name' => 'menu-footer-menu-3',
    'link_path' => 'node/5638',
    'router_path' => 'node/%',
    'link_title' => 'Ledige stillinger',
    'options' => array(
      'attributes' => array(
        'title' => 'Stillingsopslag ved Vejle Bibliotekerne',
      ),
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => -47,
  );
  // Exported menu link: menu-footer-menu-3:node/5644
  $menu_links['menu-footer-menu-3:node/5644'] = array(
    'menu_name' => 'menu-footer-menu-3',
    'link_path' => 'node/5644',
    'router_path' => 'node/%',
    'link_title' => 'In English',
    'options' => array(
      'attributes' => array(
        'title' => 'The main pages of the homepage in English and links for foreigners in Denmark',
      ),
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -48,
  );
  // Exported menu link: menu-footer-menu-3:node/5654
  $menu_links['menu-footer-menu-3:node/5654'] = array(
    'menu_name' => 'menu-footer-menu-3',
    'link_path' => 'node/5654',
    'router_path' => 'node/%',
    'link_title' => 'Organisation',
    'options' => array(
      'attributes' => array(
        'title' => 'Ledelse og organisation',
      ),
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -46,
  );
  // Exported menu link: menu-footer-menu-3:node/5658
  $menu_links['menu-footer-menu-3:node/5658'] = array(
    'menu_name' => 'menu-footer-menu-3',
    'link_path' => 'node/5658',
    'router_path' => 'node/%',
    'link_title' => 'Gebyrer',
    'options' => array(
      'attributes' => array(
        'title' => 'Gebyrer og erstatningspriser',
      ),
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -49,
  );
  // Exported menu link: menu-footer-menu-4:http://ding2.vejlebib.dk/personale
  $menu_links['menu-footer-menu-4:http://ding2.vejlebib.dk/personale'] = array(
    'menu_name' => 'menu-footer-menu-4',
    'link_path' => 'http://ding2.vejlebib.dk/personale',
    'router_path' => '',
    'link_title' => 'Personale',
    'options' => array(
      'attributes' => array(
        'title' => 'Samlet liste over direkte telefonnumre og mailadresser til Vejle Bibliotekernes personale',
      ),
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -49,
  );
  // Exported menu link: menu-footer-menu-4:http://ding2.vejlebib.dk/personale#afd
  $menu_links['menu-footer-menu-4:http://ding2.vejlebib.dk/personale#afd'] = array(
    'menu_name' => 'menu-footer-menu-4',
    'link_path' => 'http://ding2.vejlebib.dk/personale#afd',
    'router_path' => '',
    'link_title' => 'Centerbiblioteker/afdelinger',
    'options' => array(
      'attributes' => array(
        'title' => 'Samlet liste over direkte telefonnumre og mailadresser til Vejle Bibliotekernes centerbiblioteker og afdelinger',
      ),
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -48,
  );
  // Exported menu link: menu-footer-menu-4:node/5414
  $menu_links['menu-footer-menu-4:node/5414'] = array(
    'menu_name' => 'menu-footer-menu-4',
    'link_path' => 'node/5414',
    'router_path' => 'node/%',
    'link_title' => 'EAN og CVR-nummer',
    'options' => array(
      'attributes' => array(
        'title' => 'Vejle Bibliotekernes EAN- og CVR-nummer',
      ),
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
  );
  // Translatables
  // Included for use with string extractors like potx.
  t('Arrangementsklubben');
  t('Biblioteksbussen');
  t('Biblioteksintroduktion');
  t('Bibliotekspolitik');
  t('Børkop Bibliotek');
  t('Centerbiblioteker/afdelinger');
  t('Centralbibliotek');
  t('DR Romanklubben');
  t('EAN og CVR-nummer');
  t('Egtved Bibliotek');
  t('Gebyrer');
  t('Give Bibliotek');
  t('Gratis retshjælp');
  t('In English');
  t('Jelling Bibliotek');
  t('Ledige stillinger');
  t('Læsekredse');
  t('Organisation');
  t('Personale');
  t('Reglement');
  t('Strategi 2011-2014');
  t('Svært ved at komme på biblioteket?');
  t('Svært ved at læse?');
  t('Vejle Bibliotek');


  return $menu_links;
}
