<?php
/**
 * @file
 * Code for the Vejlebib Views and Panels feature.
 */

include_once 'vejlebib_views_panels.features.inc';

/**
 * Implements hook_ctools_plugin_directory().
 *
 * Tells panels where to find plugins.
 */
function vejlebib_views_panels_ctools_plugin_directory($module, $plugin) {
  if ($module == 'ctools' && !empty($plugin)) {
    return "plugins/$plugin";
  }
}

/**
 * Implements hook_block_info().
 */
function vejlebib_views_panels_block_info() {
  $blocks = array();

  $blocks['vejlebib-nav-helpers'] = array(
    'info' => t('Vejlebib nav help links'),
    'cache' => '', // What type cache to use?
  );

  return $blocks;
}

/**
 * Implements hook_theme().
 */
function vejlebib_views_panels_theme($existing, $type, $theme, $path) {
  return array(
    'vejlebib_views_panels_ding_userinfo' => array(
      'variables' => array('name' => NULL, 'pickup' => array(), 'reservation' => array(), 'debt' => array(), 'loan' => array(), 'bookmark' => array()),
      'template' => 'vejlebib_views_panels_ding_userinfo',
      'path' => $path . '/templates',
    ),
  );
}

/**
 * Implements hook_block_view().
 */
function vejlebib_views_panels_block_view($delta) {
  $block = array();
  $content = array();
  global $user;

  switch ($delta) {
    case 'vejlebib-nav-helpers':
      // Nav helper links markup
      $content[] = array(
          '#type' => 'markup',
          '#markup' => '<ul class="nav-helpers"><li><a class="english" href="/in-english">English</a></li><li><a class="read" href="http://adgangforalle.dk">Læs op</a></li><li><a class="facebook" href="https://www.facebook.com/vejlebibliotekerne" target="_blank">Facebook</a></li></ul>',
        );
      // Temporary disabled print menu:
      /*<li><a class="print" href="javascript:window.print();">Print</a></li>*/
      // Define the block.
      $block['content'] = $content;
      break;
  }

  return $block;
}
